version: "3"
services:
  traefik:
    image: traefik:v2.9
    command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.swarmMode=true"
        - "--providers.docker.exposedByDefault=false"
        - "--entrypoints.http.address=:80"
        - "--entrypoints.http.http.redirections.entryPoint.to=https"
        - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
        - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
        - "--entrypoints.https.address=:443"
        - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
        - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=http"
        - "--certificatesresolvers.letsencryptresolver.acme.email=${ACME_EMAIL}"
        - "--certificatesresolvers.letsencryptresolver.acme.storage=/etc/traefik/letsencrypt/acme.json"
        - "--certificatesresolvers.letsencryptresolver.acme.caServer=${CA_SERVER_ADDRESS}"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-ssl-volume:/etc/traefik/letsencrypt/
    networks:
      - traefik-public
    env_file:
      - ./.env.dev

networks:
  traefik-public:
    external: true

volumes:
  traefik-ssl-volume:
