services:
  todo-db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: tododb
    volumes:
      - todo-db-volume:/var/lib/postgresql/data

  todo-api:
    image: valdecimpj/todo-api:latest
    restart: always
    ports:
      - "80:80"

volumes:
    todo-db-volume:    