name: Creating File Test

on:
  push:
    branches:
      - main
      
jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Create test file
        run: echo "teste" > /teste.txt
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Created test file.
