name: Docker Hub Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run xUnit Tests
        run: dotnet test
          
      - name: Build and Publish Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Todo.Api
          push: true
          tags: ghcr.io/valdecimpj/todo-api:latest
        env:
          DOCKER_USERNAME: valdecimpj
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          
