name: Docker Hub Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run xUnit Tests
        run: dotnet test
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Publish Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Todo.Api
          push: true
          tags: valdecimpj/todo-api:latest
